jobs:
  build:
    name: macOS Java SE ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Oracle Java SE
      uses: oracle-actions/setup-java@main
      with:
        release: ${{ matrix.java }}
        website: oracle.com
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml -Parm
    strategy:
      matrix:
        java:
        - 17
        - 21
        - 22
name: Tribuo CI (macOS aarch64, Java SE 17, 21, 22)
on:
  repository_dispatch:
    types: trigger-ga___maven-macos-aarch64.yml
