jobs:
  build:
    name: Windows Java SE ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Oracle Java SE
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ matrix.java }}
        website: oracle.com
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    strategy:
      matrix:
        java:
        - 17
        - 21
        - 22
name: Tribuo CI (Windows x86_64, Java SE 17, 21, 22)
on:
  repository_dispatch:
    types: trigger-ga___maven-windows.yml
